services:
  db:
    image: postgres
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      PGUSER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    restart: always
    ports:
      - ${APP_PORT}:3000
    depends_on:
      - db
    command: bun dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - POSTGRES_HOST=db # connect to the Postgres container with Docker Networking
      - POSTGRES_PORT=5432 # use internal port of Postgres container
volumes:
  pgdata:
  node_modules:

