version: '3.8'

services:
  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=medium
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d medium -U postgres" ]
      interval: 1s
      timeout: 5s
      retries: 10
    # This allows accessing externally from "localhost" in addition to "127.0.0.1"
    ports:
      - 5432:5432

  app:
    image: node:20-bullseye
    restart: unless-stopped

    volumes:
      - ..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

    # depends_on:
    #   - db
    # environment:
    #   - POSTGRES_HOST=db # connect to the Postgres container with Docker Networking
    #   - POSTGRES_PORT=5432 # use internal port of Postgres container

volumes:
  postgres-data:
